#!/usr/bin/env python3
"""Extract the speech data tables from original/GOVOR.dsk and emit data.go.

GOVOR.dsk is an Apple DOS 3.3 disk image holding the file "gowor": a one-line
Applesoft BASIC stub (`0 CALL 2347`) followed by ~6 KB of 6502 machine code
and data, loaded at $0801.

The pieces we need for the Go port:
  * $0B70-$0C03  letter table: 4 bytes per character code $5B..$7F,
                 little-endian (start, end) addresses of the waveform segment
  * $0C00-$1DFF  waveform data (speaker delay streams)
  * $0AF0-$0B6F  spoken words for '*' '+' ',' '-' '.' '/' and digits 0-9,
                 8 bytes per slot, KOI-7 N2 (Pravetz-82) Cyrillic codes

Usage: python3 tools/extract.py original/GOVOR.dsk | gofmt > data.go
"""

import sys

DATA_BASE = 0x0C00
DATA_END = 0x1E00
LETTER_TABLE = 0x0B70
WORD_TABLE = 0x0AF0


def read_dos33_file(disk, first_track, first_sector):
    """Follow a DOS 3.3 track/sector list and return the file contents."""

    def sector(t, s):
        off = (t * 16 + s) * 256
        return disk[off:off + 256]

    out = b''
    t, s = first_track, first_sector
    while t or s:
        tsl = sector(t, s)
        nt, ns = tsl[1], tsl[2]
        for i in range(0x0C, 0x100, 2):
            dt, ds = tsl[i], tsl[i + 1]
            if dt or ds:
                out += sector(dt, ds)
        t, s = nt, ns
    return out


def find_catalog_entry(disk, name):
    def sector(t, s):
        off = (t * 16 + s) * 256
        return disk[off:off + 256]

    vtoc = sector(17, 0)
    t, s = vtoc[1], vtoc[2]
    while t or s:
        cat = sector(t, s)
        for i in range(7):
            e = cat[0x0B + i * 0x23:0x0B + (i + 1) * 0x23]
            if e[0] in (0, 0xFF):
                continue
            ename = bytes(b & 0x7F for b in e[3:3 + 30]).decode('ascii', 'replace').rstrip()
            if ename == name:
                return e[0], e[1]
        t, s = cat[1], cat[2]
    raise SystemExit(f'file {name!r} not found in catalog')


def main():
    disk = open(sys.argv[1], 'rb').read()
    t, s = find_catalog_entry(disk, 'gowor')
    raw = read_dos33_file(disk, t, s)
    length = raw[0] | (raw[1] << 8)
    body = raw[2:2 + length]

    mem = bytearray(0x10000)
    mem[0x0801:0x0801 + len(body)] = body

    blob = mem[DATA_BASE:DATA_END]

    print('// Code generated by tools/extract.py from original/GOVOR.dsk; DO NOT EDIT.')
    print()
    print('package main')
    print()
    print('// soundData is the raw speaker-delay waveform data from $0C00-$1DFF of')
    print('// the original program. Segment offsets below index into this slice.')
    print('var soundData = []byte{')
    for i in range(0, len(blob), 16):
        row = ', '.join(f'0x{b:02X}' for b in blob[i:i + 16])
        print(f'\t{row}, // ${DATA_BASE + i:04X}')
    print('}')
    print()
    print('// segments maps Pravetz-82 character codes $5B-$7F to [start, end)')
    print('// offsets within soundData (original table at $0B70).')
    print('var segments = map[byte]segment{')
    names = {0x5B: 'ш', 0x5C: 'э (unused/broken in original)', 0x5D: 'щ (= ш + т)',
             0x5E: 'ч', 0x5F: '_ (short pause)', 0x60: 'ю (= й + у)', 0x61: 'а',
             0x62: 'б', 0x63: 'ц', 0x64: 'д', 0x65: 'е', 0x66: 'ф', 0x67: 'г',
             0x68: 'х', 0x69: 'и', 0x6A: 'й', 0x6B: 'к', 0x6C: 'л', 0x6D: 'м',
             0x6E: 'н', 0x6F: 'о', 0x70: 'п', 0x71: 'я (glide + а)', 0x72: 'р',
             0x73: 'с', 0x74: 'т', 0x75: 'у', 0x76: 'ж', 0x77: 'в',
             0x78: 'ь (= й)', 0x79: 'ъ', 0x7A: 'з'}
    for ch in range(0x5B, 0x7B):  # $7B-$7F are empty/garbage entries
        i = LETTER_TABLE + (ch - 0x5B) * 4
        start = mem[i] | (mem[i + 1] << 8)
        end = mem[i + 2] | (mem[i + 3] << 8)
        if ch == 0x5C:
            # The э entry is (start == end); the original would run off the end
            # of the table (a latent bug, never hit by Bulgarian text). Skip it.
            continue
        print(f'\t0x{ch:02X}: {{0x{start - DATA_BASE:04X}, 0x{end - DATA_BASE:04X}}}, // {names[ch]}')
    print('}')
    print()
    print('// symbolWords holds what the synthesizer speaks for characters')
    print("// '*' + , - . / and the digits 0-9 (original table at $0AF0).")
    print('// Each word is given in Pravetz character codes.')
    print('var symbolWords = map[rune][]byte{')
    chars = "*+,-./0123456789"
    for slot, ch in enumerate(chars):
        b = mem[WORD_TABLE + slot * 8:WORD_TABLE + slot * 8 + 8]
        word = bytes(x for x in b if x != 0)
        koi = {0x20: ' ', 0x5B: 'ш', 0x5E: 'ч', 0x60: 'ю', 0x61: 'а', 0x62: 'б',
               0x63: 'ц', 0x64: 'д', 0x65: 'е', 0x66: 'ф', 0x67: 'г', 0x68: 'х',
               0x69: 'и', 0x6A: 'й', 0x6B: 'к', 0x6C: 'л', 0x6D: 'м', 0x6E: 'н',
               0x6F: 'о', 0x70: 'п', 0x71: 'я', 0x72: 'р', 0x73: 'с', 0x74: 'т',
               0x75: 'у', 0x76: 'ж', 0x77: 'в', 0x78: 'ь', 0x79: 'ъ', 0x7A: 'з'}
        text = ''.join(koi.get(x, '?') for x in word)
        items = ', '.join(f'0x{x:02X}' for x in word)
        print(f"\t'{ch}': {{{items}}}, // {text!r}")
    print('}')


if __name__ == '__main__':
    main()
